# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableJetifier=true

FLIPPER_VERSION=0.125.0

reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

newArchEnabled=false

hermesEnabled=true

# Signing configuration for release builds
KINGLIKE_RELEASE_STORE_FILE=keystores/kinglikeluxury-key.keystore
KINGLIKE_RELEASE_KEY_ALIAS=kinglikeluxury
KINGLIKE_RELEASE_STORE_PASSWORD=kinglikeluxury123
KINGLIKE_RELEASE_KEY_PASSWORD=kinglikeluxury123
